import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Server, Database, Lock, Globe, Building2, Workflow, ArrowRight, ArrowLeft } from 'lucide-react';
import './ZeroDayIntake.css';

// ─── Types ────────────────────────────────────────────────────────────────────

type Industry = 'finance' | 'healthcare' | 'media' | 'legal' | 'real-estate' | 'other';
type DeploymentType = 'hosted' | 'on-premise' | 'hybrid';
type CompanySize = 'startup' | 'sme' | 'enterprise';

type DataSource =
    'internal-docs' | 'databases' | 'apis' | 'web-scraping' |
    'real-time-feeds' | 'crm' | 'erp' | 'clinical-records' | 'other';

type Compliance = 'sox' | 'hipaa' | 'gdpr' | 'pci-dss' | 'sec-finra' | 'none';

interface FormState {
    clientName: string;
    clientEmail: string;
    companyName: string;
    industry: Industry | '';
    companySize: CompanySize | '';
    primaryUseCase: string;
    dataSourceTypes: DataSource[];
    complianceRequirements: Compliance[];
    deploymentType: DeploymentType | '';
    sovereignRequired: boolean;
}

// ─── IntakeStepper ────────────────────────────────────────────────────────────

const STEPS = [
  { id: 'identity',     label: 'Identity',   icon: '👤' },
  { id: 'operations',   label: 'Ops',         icon: '🏢' },
  { id: 'directive',    label: 'Directive',  icon: '🎯' },
  { id: 'architecture', label: 'Arch',        icon: '⚙️' },
];

function IntakeStepper({ currentStep, onStepClick }: { currentStep: number; onStepClick?: (i: number) => void }) {
  return (
    <div className="w-full mb-8">
      <div className="relative h-1 bg-gray-800 rounded-full mb-6">
        <motion.div
          className="absolute h-full bg-gradient-to-r from-indigo-600 to-purple-600 rounded-full"
          initial={{ width: '0%' }}
          animate={{ width: `${(currentStep / (STEPS.length - 1)) * 100}%` }}
          transition={{ duration: 0.5, ease: 'easeInOut' }}
        />
      </div>
      <div className="flex justify-between">
        {STEPS.map((step, i) => {
          const isDone = i < currentStep;
          const isActive = i === currentStep;
          return (
            <button
              key={step.id}
              onClick={() => onStepClick?.(i)}
              disabled={i > currentStep}
              className="flex flex-col items-center gap-1.5 group disabled:cursor-not-allowed"
              aria-label={step.label}
            >
              <motion.div
                className={`w-10 h-10 rounded-full flex items-center justify-center text-lg transition-all ${
                  isDone ? 'bg-indigo-600 text-white'
                  : isActive ? 'bg-indigo-600/20 border-2 border-indigo-500 text-indigo-400'
                  : 'bg-gray-800 text-gray-600 border border-gray-700'
                }`}
                animate={isActive ? { scale: [1, 1.1, 1] } : {}}
                transition={{ repeat: Infinity, duration: 2 }}
              >
                {isDone ? '✓' : step.icon}
              </motion.div>
              <span className={`text-xs font-medium transition-colors ${
                isActive ? 'text-indigo-400' : isDone ? 'text-gray-300' : 'text-gray-600'
              }`}>{step.label}</span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ─── ContractPreviewModal ─────────────────────────────────────────────────────

function ContractPreviewModal({ isOpen, form, onClose, onSend }: {
  isOpen: boolean;
  form: FormState;
  onClose: () => void;
  onSend: () => Promise<void>;
}) {
  const [isSending, setIsSending] = useState(false);
  const [sent, setSent] = useState(false);

  const contract = [
    `ZERO-DAY CLIENT SERVICES AGREEMENT`,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `CLIENT:    ${form.clientName} (${form.clientEmail})`,
    `COMPANY:   ${form.companyName}`,
    `INDUSTRY:  ${form.industry.toUpperCase()}`,
    `SCALE:     ${form.companySize.toUpperCase()}`,
    ``,
    `PRIMARY DIRECTIVE:`,
    form.primaryUseCase,
    ``,
    `DATA INTEGRATION: ${form.dataSourceTypes.join(', ') || 'None specified'}`,
    `COMPLIANCE:       ${form.complianceRequirements.join(', ') || 'None'}`,
    `DEPLOYMENT:       ${form.deploymentType.toUpperCase()}`,
    `SOVEREIGN MODE:   ${form.sovereignRequired ? 'ENABLED — Air-gapped sovereign stack' : 'STANDARD'}`,
    ``,
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
    `This agreement is auto-generated by the Zero-Day provisioning engine.`,
    `Final contract will be delivered via DocuSign within 24 hours.`,
  ].join('\n');

  async function handleSend() {
    setIsSending(true);
    try { await onSend(); setSent(true); }
    finally { setIsSending(false); }
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50" onClick={onClose} />
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="fixed inset-4 md:inset-16 z-50 bg-gray-950 rounded-2xl border border-gray-800 shadow-2xl flex flex-col overflow-hidden"
          >
            <div className="px-8 py-5 border-b border-gray-800 flex items-center justify-between shrink-0">
              <div>
                <h2 className="text-xl font-bold text-white">Contract Preview</h2>
                <p className="text-sm text-gray-400">{form.clientName} · {form.industry}</p>
              </div>
              <button onClick={onClose} className="text-gray-500 hover:text-white p-2">✕</button>
            </div>
            <div className="flex-1 overflow-y-auto p-8 min-h-0">
              {sent ? (
                <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
                  className="flex flex-col items-center justify-center h-full text-center">
                  <div className="text-6xl mb-4">✅</div>
                  <h3 className="text-2xl font-bold text-white mb-2">Boot Sequence Initiated</h3>
                  <p className="text-gray-400">Your agent network is compiling. Contract delivered to {form.clientEmail}.</p>
                </motion.div>
              ) : (
                <div className="prose prose-invert prose-sm max-w-none">
                  <pre className="whitespace-pre-wrap font-sans text-gray-300 leading-relaxed text-sm">{contract}</pre>
                </div>
              )}
            </div>
            {!sent && (
              <div className="px-8 py-5 border-t border-gray-800 flex justify-between items-center shrink-0">
                <button onClick={onClose} className="px-5 py-2.5 bg-gray-800 hover:bg-gray-700 rounded-lg text-sm text-gray-300 transition-colors">
                  Back to Edit
                </button>
                <button
                  onClick={() => void handleSend()} disabled={isSending}
                  className="px-6 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg font-semibold text-sm disabled:opacity-60 transition-opacity"
                >
                  {isSending ? 'Sending…' : '📨 Send Contract to Client'}
                </button>
              </div>
            )}
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

// ─── Constants ────────────────────────────────────────────────────────────────

const S = { label: "zdi-label", input: "zdi-input", select: "zdi-select", textarea: "zdi-textarea" };

function ChipSelect<T extends string>({ options, selected, onChange }: {
  options: { value: T; label: string; icon?: React.ReactNode }[];
  selected: T[];
  onChange: (v: T[]) => void;
}) {
  const toggle = (v: T) => onChange(selected.includes(v) ? selected.filter(s => s !== v) : [...selected, v]);
  return (
    <div className="zdi-chip-select">
      {options.map(o => {
        const isSelected = selected.includes(o.value);
        return (
          <motion.button key={o.value} type="button" whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
            onClick={() => toggle(o.value)} className={`zdi-chip-btn ${isSelected ? 'active' : 'inactive'}`}>
            {o.icon}{o.label}
          </motion.button>
        );
      })}
    </div>
  );
}

const DATA_SOURCES: { value: DataSource; label: string; icon: React.ReactNode }[] = [
  { value: 'internal-docs',   label: 'Internal Docs',  icon: <Lock size={14} /> },
  { value: 'databases',       label: 'Databases',      icon: <Database size={14} /> },
  { value: 'apis',            label: 'External APIs',  icon: <Globe size={14} /> },
  { value: 'crm',             label: 'CRM',            icon: <Building2 size={14} /> },
  { value: 'erp',             label: 'ERP',            icon: <Workflow size={14} /> },
  { value: 'other',           label: 'Other',          icon: <Server size={14} /> },
];

const COMPLIANCE_OPTIONS: { value: Compliance; label: string }[] = [
  { value: 'sox',      label: 'SOX' },
  { value: 'hipaa',   label: 'HIPAA' },
  { value: 'gdpr',    label: 'GDPR' },
  { value: 'pci-dss', label: 'PCI DSS' },
  { value: 'sec-finra', label: 'SEC/FINRA' },
  { value: 'none',    label: 'None' },
];

const initial: FormState = {
  clientName: '', clientEmail: '', companyName: '',
  industry: '', companySize: '', primaryUseCase: '',
  dataSourceTypes: [], complianceRequirements: [],
  deploymentType: '', sovereignRequired: false,
};

// ─── Step variants ────────────────────────────────────────────────────────────

const STEP_VARIANTS = {
  enter: (dir: number) => ({ opacity: 0, x: dir > 0 ? 40 : -40 }),
  center: { opacity: 1, x: 0 },
  exit:  (dir: number) => ({ opacity: 0, x: dir > 0 ? -40 : 40 }),
};

// ─── ZeroDayIntake ────────────────────────────────────────────────────────────

export default function ZeroDayIntake() {
  const [form, setForm]         = useState<FormState>(initial);
  const [step, setStep]         = useState(0);
  const [dir,  setDir]          = useState(1);
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState('');
  const [showContract, setShowContract] = useState(false);

  const set = <K extends keyof FormState>(k: K, v: FormState[K]) =>
    setForm(prev => ({ ...prev, [k]: v }));

  const goTo = (next: number) => { setDir(next > step ? 1 : -1); setStep(next); };

  const canAdvance = () => {
    if (step === 0) return !!form.clientName && !!form.clientEmail && !!form.companyName;
    if (step === 1) return !!form.industry && !!form.companySize;
    if (step === 2) return !!form.primaryUseCase;
    return !!form.deploymentType;
  };

  const handleSubmit = async () => {
    if (!form.industry || !form.deploymentType || !form.companySize) {
      setError('Please complete all required fields.'); return;
    }
    setError(''); setLoading(true);
    try {
      const res = await fetch('/api/zeroday/provision', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form),
      });
      if (!res.ok) throw new Error('Provisioning request failed');
      const data = await res.json() as { clientId: string };
      window.location.href = `/client/${data.clientId}`;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally { setLoading(false); }
  };

  return (
    <div className="zdi-container">
      <div className="zdi-ambient-glow" />
      <div className="zdi-content-wrapper">

        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="zdi-header">
          <div className="zdi-badge">W6 Intake Protocol</div>
          <h1 className="zdi-title">Boot Your Sovereign<br />Intelligence Engine.</h1>
          <p className="zdi-subtitle">
            No engineers. No devops. Define your operational boundaries and our Zero-Day Worker will compile your dedicated agent network in seconds.
          </p>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.2 }} className="zdi-form">

          <IntakeStepper currentStep={step} onStepClick={(i) => { if (i < step) goTo(i); }} />

          <div className="relative overflow-hidden min-h-[300px]">
            <AnimatePresence custom={dir} mode="wait">
              <motion.div
                key={step} custom={dir}
                variants={STEP_VARIANTS} initial="enter" animate="center" exit="exit"
                transition={{ duration: 0.28, ease: 'easeInOut' }}
              >

                {step === 0 && (
                  <div className="flex flex-col gap-4">
                    <div className="zdi-section-title">01 / Identity</div>
                    <div className="zdi-grid-2">
                      <div>
                        <label className={S.label}>Your Name</label>
                        <input className={S.input} value={form.clientName} onChange={e => set('clientName', e.target.value)} required placeholder="Jane Smith" />
                      </div>
                      <div>
                        <label className={S.label}>Work Email</label>
                        <input className={S.input} type="email" value={form.clientEmail} onChange={e => set('clientEmail', e.target.value)} required placeholder="jane@company.com" />
                      </div>
                      <div className="zdi-grid-full">
                        <label className={S.label}>Company Matrix</label>
                        <input className={S.input} value={form.companyName} onChange={e => set('companyName', e.target.value)} required placeholder="Acme Capital" />
                      </div>
                    </div>
                  </div>
                )}

                {step === 1 && (
                  <div className="flex flex-col gap-4">
                    <div className="zdi-section-title">02 / Operations</div>
                    <div className="zdi-grid-2">
                      <div>
                        <label className={S.label}>Industry Vertical</label>
                        <div className="zdi-select-wrapper">
                          <select title="Industry Vertical" className={S.select} value={form.industry} onChange={e => set('industry', e.target.value as Industry)} required>
                            <option value="" disabled>Select vertical</option>
                            <option value="finance">Finance</option>
                            <option value="healthcare">Healthcare</option>
                            <option value="media">Media &amp; Creative</option>
                            <option value="legal">Legal</option>
                            <option value="real-estate">Real Estate</option>
                            <option value="other">Other</option>
                          </select>
                          <div className="zdi-select-arrow">▼</div>
                        </div>
                      </div>
                      <div>
                        <label className={S.label}>Scale</label>
                        <div className="zdi-select-wrapper">
                          <select title="Company Scale" className={S.select} value={form.companySize} onChange={e => set('companySize', e.target.value as CompanySize)} required>
                            <option value="" disabled>Select scale</option>
                            <option value="startup">Startup (&lt;50 nodes)</option>
                            <option value="sme">SME (50–500 nodes)</option>
                            <option value="enterprise">Enterprise (500+ nodes)</option>
                          </select>
                          <div className="zdi-select-arrow">▼</div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {step === 2 && (
                  <div className="flex flex-col gap-4">
                    <div className="zdi-section-title">03 / Primary Directive</div>
                    <div>
                      <label className={S.label}>Objective Vector</label>
                      <textarea className={S.textarea} value={form.primaryUseCase} onChange={e => set('primaryUseCase', e.target.value)} required
                        placeholder="e.g. Ingest daily market feeds, analyze sentiment against our portfolio, and pre-draft risk assessments." />
                    </div>
                    <div>
                      <label className={S.label}>Data Integration Endpoints</label>
                      <ChipSelect options={DATA_SOURCES} selected={form.dataSourceTypes} onChange={v => set('dataSourceTypes', v)} />
                    </div>
                  </div>
                )}

                {step === 3 && (
                  <div className="flex flex-col gap-4">
                    <div className="zdi-section-title">04 / Architecture &amp; Governance</div>
                    <div>
                      <label className={`${S.label} zdi-mb-12`}>Constitutional Compliance Frameworks</label>
                      <ChipSelect options={COMPLIANCE_OPTIONS} selected={form.complianceRequirements} onChange={v => set('complianceRequirements', v)} />
                    </div>
                    <div className="zdi-grid-2">
                      <div>
                        <label className={S.label}>Deployment Topology</label>
                        <div className="zdi-select-wrapper">
                          <select title="Deployment Topology" className={S.select} value={form.deploymentType} onChange={e => set('deploymentType', e.target.value as DeploymentType)} required>
                            <option value="" disabled>Select topology</option>
                            <option value="hosted">Zero-Day Cloud (Managed)</option>
                            <option value="on-premise">Air-Gapped (On-Premise)</option>
                            <option value="hybrid">Hybrid Interconnect</option>
                          </select>
                          <div className="zdi-select-arrow">▼</div>
                        </div>
                      </div>
                      <div
                        className={`zdi-sovereign-toggle ${form.sovereignRequired ? 'active' : 'inactive'}`}
                        onClick={() => set('sovereignRequired', !form.sovereignRequired)}
                      >
                        <div className={`zdi-sovereign-switch ${form.sovereignRequired ? 'active' : 'inactive'}`}>
                          <div className={`zdi-sovereign-thumb ${form.sovereignRequired ? 'active' : 'inactive'}`} />
                        </div>
                        <div>
                          <div className={`zdi-sovereign-label ${form.sovereignRequired ? 'active' : 'inactive'}`}>Sovereign Mode</div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

              </motion.div>
            </AnimatePresence>
          </div>

          {error && <div className="zdi-error">{error}</div>}

          {/* Navigation */}
          <div className="flex gap-3 mt-6">
            {step > 0 && (
              <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} type="button"
                onClick={() => goTo(step - 1)}
                className="px-5 py-2.5 bg-gray-800 hover:bg-gray-700 rounded-xl text-sm text-gray-300 flex items-center gap-2 transition-colors">
                <ArrowLeft size={16} /> Back
              </motion.button>
            )}
            {step < STEPS.length - 1 ? (
              <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} type="button"
                onClick={() => goTo(step + 1)} disabled={!canAdvance()}
                className={`flex-1 zdi-submit-btn ${!canAdvance() ? 'loading' : 'idle'} flex items-center justify-center gap-2`}>
                Next Step <ArrowRight size={16} />
              </motion.button>
            ) : (
              <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} type="button"
                onClick={() => setShowContract(true)} disabled={!canAdvance() || loading}
                className="flex-1 zdi-submit-btn idle flex items-center justify-center gap-2">
                Preview Contract <ArrowRight size={20} />
              </motion.button>
            )}
          </div>

        </motion.div>
      </div>

      <ContractPreviewModal isOpen={showContract} form={form} onClose={() => setShowContract(false)} onSend={handleSubmit} />
    </div>
  );
}
