/**
 * SENTINEL Agent Quality Gate
 * 
 * Quality gate for the SENTINEL agent. Validates all BOLT-generated code
 * through ReSharper analysis. Blocks merge on Class 3 constitutional violations.
 * 
 * @package code-quality
 * @issue #34 — HELIX C
 * @agent COMET (AURORA hive)
 */

import { ReSharperCLI, ReSharperConfig, InspectionResult, ConstitutionalClass } from './resharper-cli';
import { ConstitutionalMapper, ComplianceReport } from './constitutional-mapper';

// ─── Types ───────────────────────────────────────────────────

export interface GateResult {
  passed: boolean;
  inspectionResult: InspectionResult;
  complianceReport: ComplianceReport;
  prComment: string;
  autoFixSuggestions: string[];
}

export interface SentinelGateConfig {
  resharperConfig: ReSharperConfig;
  blockOnClass3: boolean;
  generatePrComment: boolean;
  maxClass2Allowed: number;
}

// ─── SENTINEL Gate ───────────────────────────────────────

export class SentinelGate {
  private cli: ReSharperCLI;
  private mapper: ConstitutionalMapper;
  private config: SentinelGateConfig;

  constructor(config: SentinelGateConfig) {
    this.config = config;
    this.cli = new ReSharperCLI(config.resharperConfig);
    this.mapper = new ConstitutionalMapper();
  }

  /**
   * Run the full quality gate on a solution/project.
   * Used by SENTINEL agent during PR review.
   */
  async runGate(targetPath?: string): Promise<GateResult> {
    const inspection = await this.cli.inspect(targetPath);
    const report = this.mapper.generateReport(inspection.issues);

    const passed = this.evaluateGate(inspection, report);
    const prComment = this.config.generatePrComment
      ? this.buildPrComment(inspection, report, passed)
      : '';

    return {
      passed,
      inspectionResult: inspection,
      complianceReport: report,
      prComment,
      autoFixSuggestions: this.extractFixSuggestions(inspection),
    };
  }

  /**
   * Run pre-commit hook on staged files.
   */
  async runPreCommitHook(stagedFiles: string[]): Promise<GateResult> {
    const inspection = await this.cli.inspectFiles(stagedFiles);
    const report = this.mapper.generateReport(inspection.issues);
    const passed = this.evaluateGate(inspection, report);

    return {
      passed,
      inspectionResult: inspection,
      complianceReport: report,
      prComment: '',
      autoFixSuggestions: this.extractFixSuggestions(inspection),
    };
  }

  private evaluateGate(inspection: InspectionResult, report: ComplianceReport): boolean {
    if (this.config.blockOnClass3 && inspection.class3Count > 0) return false;
    if (inspection.class2Count > this.config.maxClass2Allowed) return false;
    return true;
  }

  private buildPrComment(
    inspection: InspectionResult,
    report: ComplianceReport,
    passed: boolean,
  ): string {
    const status = passed ? '✅ PASSED' : '❌ BLOCKED';
    const lines: string[] = [
      `## 🛡️ SENTINEL Quality Gate: ${status}`,
      '',
      `**Constitutional Compliance Score:** ${report.complianceScore}/100`,
      '',
      '| Class | Count | Status |',
      '|-------|-------|--------|',
      `| Class 3 (Error) | ${inspection.class3Count} | ${inspection.class3Count > 0 ? '❌ Blocks merge' : '✅'} |`,
      `| Class 2 (Warning) | ${inspection.class2Count} | ${inspection.class2Count > this.config.maxClass2Allowed ? '⚠️ Over limit' : '✅'} |`,
      `| Class 1 (Suggestion) | ${inspection.class1Count} | ℹ️ |`,
      '',
      `**Total Issues:** ${inspection.totalIssues} across ${inspection.inspectedFiles} files`,
      '',
    ];

    if (!passed) {
      lines.push('### Required Actions');
      lines.push('');
      const class3Issues = inspection.issues.filter(
        i => i.constitutionalClass === ConstitutionalClass.CLASS_3,
      );
      for (const issue of class3Issues.slice(0, 10)) {
        lines.push(`- **${issue.file}:${issue.line}** — ${issue.message}`);
      }
      if (class3Issues.length > 10) {
        lines.push(`- ...and ${class3Issues.length - 10} more`);
      }
    }

    lines.push('', '---', '*Generated by SENTINEL agent via ReSharper Constitutional Gate*');
    return lines.join('\n');
  }

  private extractFixSuggestions(inspection: InspectionResult): string[] {
    return inspection.issues
      .filter(i => i.constitutionalClass === ConstitutionalClass.CLASS_3)
      .map(i => `${i.file}:${i.line} — ${i.typeId}: ${i.message}`);
  }
}

export default SentinelGate;