/**
 * build.js — Style Dictionary build script for Inception Engine design tokens
 *
 * Compiles tokens.json into:
 *   dist/css/tokens.css       — CSS custom properties
 *   dist/scss/_tokens.scss    — SCSS variables
 *   dist/js/tokens.js         — CommonJS module
 *   dist/js/tokens.esm.js     — ES module
 *   dist/json/tokens.json     — Resolved flat JSON
 *   dist/tailwind/tokens.js   — Tailwind theme extension
 *
 * Usage:
 *   node build.js              # build all platforms
 *   node build.js --watch      # watch mode (requires chokidar)
 *   node build.js --platform css  # single platform
 */

'use strict';

const StyleDictionary = require('style-dictionary');
const path = require('path');
const fs = require('fs');

const SRC   = path.join(__dirname, 'tokens.json');
const DIST  = path.join(__dirname, 'dist');
const PLATFORMS = ['css', 'scss', 'js', 'json', 'tailwind'];

// ─── Custom transforms ───────────────────────────────────────────────────────

// Strip quotes from font family values for CSS
StyleDictionary.registerTransform({
  name: 'value/font-family-clean',
  type: 'value',
  matcher: (token) => token.type === 'fontFamily',
  transformer: (token) => token.value,
});

// Convert cubicBezier type to CSS transition-timing-function string
StyleDictionary.registerTransform({
  name: 'value/cubic-bezier',
  type: 'value',
  matcher: (token) => token.type === 'cubicBezier',
  transformer: (token) => token.value,
});

// ─── Custom formats ──────────────────────────────────────────────────────────

// ES module output
StyleDictionary.registerFormat({
  name: 'javascript/es-module',
  formatter: ({ dictionary }) => {
    const tokens = {};
    dictionary.allTokens.forEach((token) => {
      const key = token.path.join('.');
      tokens[key] = token.value;
    });
    return `// Auto-generated by design-tokens/build.js — DO NOT EDIT\n// Source: tokens.json\n\nexport const tokens = ${JSON.stringify(tokens, null, 2)}\n\nexport default tokens;\n`;
  },
});

// Tailwind theme extension
StyleDictionary.registerFormat({
  name: 'javascript/tailwind',
  formatter: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const fontSize = {};
    const fontWeight = {};
    const lineHeight = {};
    const letterSpacing = {};
    const borderRadius = {};
    const boxShadow = {};
    const transitionDuration = {};
    const transitionTimingFunction = {};
    const zIndex = {};

    dictionary.allTokens.forEach((token) => {
      const [cat, ...rest] = token.path;
      const key = rest.join('-').replace(/\./g, '_');

      switch (cat) {
        case 'color':
          // Only export semantic tokens to Tailwind
          if (token.path[1] === 'semantic') {
            const twKey = token.path.slice(2).join('-');
            colors[twKey] = token.value;
          }
          break;
        case 'spacing':       spacing[key] = token.value; break;
        case 'typography':
          if (token.path[1] === 'fontSize')     fontSize[key]     = token.value;
          if (token.path[1] === 'fontWeight')   fontWeight[key]   = token.value;
          if (token.path[1] === 'lineHeight')   lineHeight[key]   = token.value;
          if (token.path[1] === 'letterSpacing') letterSpacing[key] = token.value;
          break;
        case 'borderRadius':  borderRadius[key] = token.value; break;
        case 'shadow':        boxShadow[key]    = token.value; break;
        case 'animation':
          if (token.path[1] === 'duration') transitionDuration[key]      = token.value;
          if (token.path[1] === 'easing')   transitionTimingFunction[key] = token.value;
          break;
        case 'zIndex':        zIndex[key] = token.value; break;
      }
    });

    const theme = {
      colors,
      spacing,
      fontSize,
      fontWeight,
      lineHeight,
      letterSpacing,
      borderRadius,
      boxShadow,
      transitionDuration,
      transitionTimingFunction,
      zIndex,
    };

    return `// Auto-generated by design-tokens/build.js — DO NOT EDIT\n// Paste into tailwind.config.js as: theme: { extend: require('./design-tokens/dist/tailwind/tokens') }\n\n/** @type {import('tailwindcss').Config['theme']} */\nmodule.exports = ${JSON.stringify(theme, null, 2)};\n`;
  },
});

// ─── Platform configs ────────────────────────────────────────────────────────

const config = {
  source: [SRC],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: 'ie', // inception-engine prefix
      buildPath: path.join(DIST, 'css') + '/',
      files: [{
        destination: 'tokens.css',
        format: 'css/variables',
        options: {
          outputReferences: true,
          selector: ':root',
        },
      }],
    },
    scss: {
      transformGroup: 'scss',
      prefix: 'ie',
      buildPath: path.join(DIST, 'scss') + '/',
      files: [{
        destination: '_tokens.scss',
        format: 'scss/variables',
        options: { outputReferences: true },
      }],
    },
    js: {
      transformGroup: 'js',
      buildPath: path.join(DIST, 'js') + '/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/module',
        },
        {
          destination: 'tokens.esm.js',
          format: 'javascript/es-module',
        },
      ],
    },
    json: {
      transformGroup: 'js',
      buildPath: path.join(DIST, 'json') + '/',
      files: [{
        destination: 'tokens.json',
        format: 'json/flat',
      }],
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: path.join(DIST, 'tailwind') + '/',
      files: [{
        destination: 'tokens.js',
        format: 'javascript/tailwind',
      }],
    },
  },
};

// ─── Build ───────────────────────────────────────────────────────────────────

function ensureDirs() {
  ['css', 'scss', 'js', 'json', 'tailwind'].forEach((p) => {
    const dir = path.join(DIST, p);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  });
}

function build(platform) {
  ensureDirs();
  const sd = StyleDictionary.extend({
    ...config,
    platforms: platform
      ? { [platform]: config.platforms[platform] }
      : config.platforms,
  });
  sd.buildAllPlatforms();
  console.log(`\n✅ Design tokens built${platform ? ' [' + platform + ']' : ' [all platforms]'}`);
  console.log(`   Output: ${DIST}/`);
}

// ─── CLI entry ───────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const platformArg = args.find((a) => a.startsWith('--platform='));
const platform = platformArg ? platformArg.split('=')[1] : null;

if (platform && !PLATFORMS.includes(platform)) {
  console.error(`Unknown platform "${platform}". Choose from: ${PLATFORMS.join(', ')}`);
  process.exit(1);
}

build(platform);
