/**
 * COMET — Type System
 *
 * The intermediate representation (IR) that bridges the world of natural language
 * instructions and the physical reality of browser/native app actions.
 *
 * MixedActionPlan: the compiled execution program.
 * - UINode: a physical interaction with the GUI world
 * - PythonNode: in-process logic (data extraction, conditionals, math)
 * - ConditionalNode: branching based on runtime state
 *
 * Think of it like: the SMG is the map, the MixedActionPlan is the route,
 * the Executor is the driver.
 */

import { z } from 'zod';

// ─── SMG Types (inlined from @inception/ghost) ────────────────────────────────
// Ghost package has no subpath exports yet, so we define the shapes here
// as the single canonical source of truth used across the COMET package.

export interface SMGElement {
    id: string;
    label: string;
    selector: string;
    staleness_score?: number;
    validated_at?: string;
}

export interface SMGState {
    id: string;
    label: string;
    url_pattern: string;
    url_example: string;
    lynch_type: string;
    inbound_count: number;
    elements: SMGElement[];
}

export interface SMGGraph {
    domain: string;
    version?: number;
    coverage_score: number;
    staleness_score: number;
    total_states: number;
    states: Record<string, SMGState>;
}

// ─── Action Context ───────────────────────────────────────────────────────────
// Shared variable scope across all plan nodes.
// Output of step N is available to step N+1 via context.get('var_name').

export type ActionContext = Map<string, string | number | boolean | null | Record<string, unknown>>;

// ─── Node Types ───────────────────────────────────────────────────────────────

// A physical GUI interaction — click, fill, navigate, read
export const UINodeSchema = z.object({
    type: z.literal('ui'),
    node_id: z.string(),            // Plan-local unique ID
    description: z.string(),        // Human-readable: "Click the Submit button"
    selector: z.string(),           // Playwright CSS/ARIA or Appium selector
    action: z.enum(['click', 'fill', 'navigate', 'read', 'scroll', 'hover', 'wait']),
    input: z.string().optional(),   // For 'fill': the value to type (may be ${var})
    output_var: z.string().optional(), // For 'read': store extracted text into this var name
    state_id: z.string().optional(), // SMG state this node belongs to
    element_id: z.string().optional(), // SMG element ID
    timeout_ms: z.number().default(15000),
    retry_count: z.number().default(2),
    // Constitutional metadata
    reads_pii: z.boolean().default(false),
    writes_data: z.boolean().default(false),
    requires_confirmation: z.boolean().default(false),
});
export type UINode = z.infer<typeof UINodeSchema>;

// In-process logic: data manipulation, string formatting, math, conditional checks
export const PythonNodeSchema = z.object({
    type: z.literal('python'),
    node_id: z.string(),
    description: z.string(),
    code: z.string(),               // JS expression evaluated in sandboxed context
    input_vars: z.array(z.string()),  // Variable names from context this node reads
    output_var: z.string(),         // Result stored under this name
});
export type PythonNode = z.infer<typeof PythonNodeSchema>;

// Conditional branching
export const ConditionalNodeSchema = z.object({
    type: z.literal('conditional'),
    node_id: z.string(),
    description: z.string(),
    condition: z.string(),          // JS expression: 'context.get("price") > 100'
    then_nodes: z.array(z.string()), // node_ids to execute if true
    else_nodes: z.array(z.string()).default([]), // node_ids to execute if false
});
export type ConditionalNode = z.infer<typeof ConditionalNodeSchema>;

export const PlanNodeSchema = z.discriminatedUnion('type', [UINodeSchema, PythonNodeSchema, ConditionalNodeSchema]);
export type PlanNode = z.infer<typeof PlanNodeSchema>;

// ─── Mixed Action Plan ────────────────────────────────────────────────────────
// The compiled, validated execution program.
// Generated by: Sketch → Linker → Compiler → (PreflightReviewer) → Executor

export const MixedActionPlanSchema = z.object({
    id: z.string(),
    created_at: z.string(),
    instruction: z.string(),        // Original natural language instruction
    domain: z.string(),
    platform: z.enum(['web', 'android', 'ios', 'visionos']),
    smg_version: z.number().optional(), // SMG version this plan was compiled against
    nodes: z.array(PlanNodeSchema),
    // Execution order — linear with conditionals branching
    execution_order: z.array(z.string()), // node_ids in order
    // Preflight result (set after governance review)
    preflight: z.object({
        verdict: z.enum(['APPROVED', 'REVIEW', 'BLOCKED']),
        reasoning: z.string(),
        flagged_nodes: z.array(z.string()),
    }).optional(),
    // Estimated impact
    estimated_reads_pii: z.boolean().default(false),
    estimated_writes_data: z.boolean().default(false),
    steps_requiring_confirmation: z.array(z.string()).default([]),
});
export type MixedActionPlan = z.infer<typeof MixedActionPlanSchema>;

// ─── Execution Result ─────────────────────────────────────────────────────────

export const NodeResultSchema = z.object({
    node_id: z.string(),
    status: z.enum(['success', 'failed', 'skipped', 'repaired']),
    output: z.unknown().optional(),
    error: z.string().optional(),
    repair_attempted: z.boolean().default(false),
    repair_succeeded: z.boolean().default(false),
    duration_ms: z.number(),
    selector_used: z.string().optional(), // May differ from plan if validator repaired it
});
export type NodeResult = z.infer<typeof NodeResultSchema>;

export const ExecutionResultSchema = z.object({
    plan_id: z.string(),
    started_at: z.string(),
    completed_at: z.string(),
    duration_ms: z.number(),
    status: z.enum(['success', 'partial', 'failed', 'blocked']),
    node_results: z.array(NodeResultSchema),
    context_snapshot: z.record(z.unknown()), // Final variable state
    error: z.string().optional(),
    smg_updates: z.number().default(0), // # of SMG states updated by validator
});
export type ExecutionResult = z.infer<typeof ExecutionResultSchema>;

// ─── COMET Request/Response ───────────────────────────────────────────────────

export interface CometExecuteRequest {
    url: string;
    instruction: string;
    mode?: 'auto' | 'programmatic' | 'reactive';
    autonomy?: 'supervised' | 'autonomous'; // Default: supervised
    platform?: 'web' | 'android' | 'ios';
    device_id?: string; // Android/iOS
    bundle_id?: string; // iOS
    package?: string;   // Android
}

export interface CometExecuteResponse {
    status: 'success' | 'partial' | 'failed' | 'blocked' | 'queued';
    mode_used: 'programmatic' | 'reactive';
    smg_hit: boolean;
    plan?: MixedActionPlan;
    result?: ExecutionResult;
    preflight?: MixedActionPlan['preflight'];
    task_id: string;
    error?: string;
}
