/**
 * @cle/core — Transmission Types
 *
 * Shared types for The Transmission: an autonomous, living infinity story.
 * A world that already exists, broadcasting whether or not anyone is listening.
 */

// ── Artifact Kinds ────────────────────────────────────────────────────────────

export type ArtifactKind =
  | 'radio_log'
  | 'sensor_readout'
  | 'corrupted_file'
  | 'witness_testimony'
  | 'field_report'
  | 'system_alert'
  | 'intercepted_message';

export const ARTIFACT_KIND_LABELS: Record<ArtifactKind, string> = {
  radio_log:            'RADIO LOG',
  sensor_readout:       'SENSOR READOUT',
  corrupted_file:       'CORRUPTED FILE',
  witness_testimony:    'WITNESS TESTIMONY',
  field_report:         'FIELD REPORT',
  system_alert:         'SYSTEM ALERT',
  intercepted_message:  'INTERCEPTED MESSAGE',
};

// ── Core Artifact ─────────────────────────────────────────────────────────────

export interface TransmissionArtifact {
  /** UUID v4 */
  id: string;
  /** What kind of document this is */
  kind: ArtifactKind;
  /** ISO — when the artifact "occurred" in the story world's timeline */
  timestamp: string;
  /** ISO — wall-clock time this was generated by the daemon */
  receivedAt: string;
  /** Transmission callsign, e.g. "STATION-7 / FREQ 88.6 MHz" */
  callsign: string;
  /** Short descriptive title */
  subject: string;
  /** Full artifact body — raw document voice, 1–4 paragraphs */
  body: string;
  /**
   * Signal corruption level 0–1.
   * 0 = crystal clear, 1 = nearly unreadable.
   * Controls visual glitch intensity in the UI.
   */
  corruption: number;
  /** Monotonic world epoch counter — how far along the story is */
  worldEpoch: number;
  /** Semantic tags for cross-referencing and archive filtering */
  tags: string[];
  /** If crowd reader memory shaped this artifact, what theme drove it */
  readerInfluence?: string;
  /** Geographic/spatial reference within the story world */
  location?: string;
  /** References (by ID) to prior artifacts this one responds to */
  relatesTo?: string[];
}

// ── World State ───────────────────────────────────────────────────────────────

export interface TransmissionWorldState {
  /** Monotonic counter — increments every daemon cycle */
  epoch: number;
  /** ISO — when the story world started running */
  startedAt: string;
  /** ISO — last daemon cycle completion */
  lastUpdated: string;
  /**
   * Named factions, groups, or forces active in the world.
   * The daemon evolves these over epochs.
   */
  activeFactions: string[];
  /** The thematic undercurrent driving current artifacts */
  dominantTheme: string;
  /**
   * 0–1 signal strength.
   * High = many artifacts, rapid events.
   * Low = sparse, fragmented, harder to read.
   */
  signalStrength: number;
  /** Total artifacts generated since world start */
  artifactCount: number;
  /** Accumulated unique reader session count */
  readerCount: number;
  /** Locations that have appeared most frequently in artifacts */
  hotLocations: string[];
  /** Themes readers have lingered on longest */
  readerMemory: string[];
}

// ── Daemon → Genkit Flow I/O ──────────────────────────────────────────────────

export interface TransmissionGenerateInput {
  worldState: TransmissionWorldState;
  /** The 10 most recent artifacts, for narrative continuity */
  previousArtifacts: TransmissionArtifact[];
  /** Aggregated signals from reader behavior this epoch */
  readerSignals?: string[];
}

export interface TransmissionGenerateOutput {
  artifact: TransmissionArtifact;
}

// ── Reader Signal (anonymous interaction capture) ─────────────────────────────

export interface TransmissionReaderSignal {
  /** Artifact the reader interacted with */
  artifactId: string;
  /** Type of interaction */
  action: 'view' | 'dwell' | 'archive_search';
  /** ISO wall-clock */
  at: string;
  /** Tags from the artifact, for theme weighting */
  tags: string[];
}
