import { z } from 'genkit';
import { ai, LOCAL_MODEL_IDS, generateWithFallback, FALLBACK_CHAINS } from '../index.js';
import pLimit from 'p-limit';

/**
 * ZERO-DAY GTM SWARM
 *
 * Demonstrates the full power of "Model Symphony Orchestration".
 * 
 * 1. Cloud (Gemini 2.5 Pro): "The Brain" - Generates 50 unique campaign hooks instantly (Tier 3 Reasoning).
 * 2. Local Swarm (Gemma 3 / Qwen): "The Workers" - Parallelizes the writing of the actual copy 
 *    across 32 threads using the RTX 4090, avoiding all rate limits and API costs for the bulk work.
 */

export const ZeroDayGtmInputSchema = z.object({
    product: z.string().describe('The product or feature launching'),
    targetAudience: z.string().describe('Who we are selling this to'),
    scale: z.number().min(5).max(100).default(20).describe('How many parallel variants to generate'),
});

export const ZeroDayGtmOutputSchema = z.object({
    campaignHooks: z.array(z.string()).describe('The core concepts generated by the cloud model'),
    generatedCopy: z.array(z.object({
        hook: z.string(),
        socialPost: z.string(),
        emailSubject: z.string(),
        workerId: z.string(),
    })).describe('The final copy generated by the local swarm'),
    executionTimeMs: z.number(),
});

export type ZeroDayGtmInput = z.infer<typeof ZeroDayGtmInputSchema>;
export type ZeroDayGtmOutput = z.infer<typeof ZeroDayGtmOutputSchema>;

export const ZeroDayGtmSwarmFlow = ai.defineFlow(
    {
        name: 'ZeroDayGtmSwarm',
        inputSchema: ZeroDayGtmInputSchema,
        outputSchema: ZeroDayGtmOutputSchema,
    },
    async (input): Promise<ZeroDayGtmOutput> => {
        const startTime = Date.now();
        console.log(`[ZERO-DAY SWARM] 🚀 Initiating massive parallel GTM sequence for: ${input.product}`);
        console.log(`[ZERO-DAY SWARM] 🎯 Target Scale: ${input.scale} variants`);

        // =========================================================================
        // PHASE 1: CLOUD IDEATION (THE BRAIN)
        // Highly complex reasoning tasks go to Tier 3 Cloud (Gemini Pro)
        // =========================================================================
        console.log(`[ZERO-DAY SWARM] 🧠 PHASE 1: Cloud Ideation (Tier 3 Max Reasoning)...`);

        const ideationPrompt = `You are the Head of Growth. We are launching a new product today. 
Product: ${input.product}
Target Audience: ${input.targetAudience}

Generate exactly ${input.scale} completely unique, distinct marketing hooks or psychological angles we can use to sell this product. 
Respond ONLY with a JSON array of strings. No markdown formatting, just the raw JSON array.`;

        const { text: hooksJsonText } = await generateWithFallback(ai, {
            prompt: ideationPrompt,
            config: { temperature: 0.9 }, // High creativity for ideation
            // Note: In production you would use output.schema, but we are requesting raw text for speed here
        } as any, FALLBACK_CHAINS.tier3Max);

        let hooks: string[] = [];
        try {
            // Strip any accidental markdown blocks the LLM might have added despite prompt
            const cleanText = hooksJsonText.replace(/```json/g, '').replace(/```/g, '').trim();
            hooks = JSON.parse(cleanText);
        } catch (e) {
            console.error(`[ZERO-DAY SWARM] ❌ Failed to parse JSON from Cloud model. Raw output:`, hooksJsonText);
            throw new Error(`Cloud Ideation Parsing Failed: ${e}`);
        }

        console.log(`[ZERO-DAY SWARM] ✅ Generated ${hooks.length} unique hooks from the cloud.`);

        // =========================================================================
        // PHASE 2: LOCAL EXECUTION (THE WORKERS)
        // Bulk writing tasks go to Tier 1 Local (Gemma 3 / Qwen) running parallel
        // =========================================================================
        console.log(`[ZERO-DAY SWARM] 🏭 PHASE 2: Local Swarm Execution (Pushing to RTX 4090 / 32-thread CPU)...`);

        // We use pLimit to control exactly how many concurrent requests hit the local Ollama instance.
        // Even with a 4090, pushing 50 simultaneous LLM generations will cause OOM or timeout.
        // We limit to 3-5 concurrent depending on VRAM usage.
        const limit = pLimit(4);
        const generatedVariants: { hook: string; socialPost: string; emailSubject: string; workerId: string }[] = [];

        // Distribute the hooks to the local workers
        const workerPromises = hooks.map((hook, index) => limit(async () => {
            const workerId = `LocalWorker-${index + 1}`;
            if (index % 5 === 0) console.log(`[ZERO-DAY SWARM]   ↳ ${workerId} attacking hook: "${hook.slice(0, 30)}..."`);

            const workerPrompt = `You are an elite copywriter executing a campaign variant. 
Product: ${input.product}
Target Audience: ${input.targetAudience}
Main Hook / Angle to use: ${hook}

Write exactly one engaging social media post (max 280 chars) and one compelling email subject line based strictly on this hook.
Format your output exactly like this with exactly two lines:
SOCIAL: [Your social post here]
EMAIL: [Your email subject here]`;

            // Hit the local Gemma 3 model directly. We don't use Fallback Chains here because local is free.
            // If local fails, we might just drop the variant rather than pay cloud costs for bulk generation.
            try {
                const { text: copyText } = await ai.generate({
                    model: `ollama/${LOCAL_MODEL_IDS.fast}`,
                    prompt: workerPrompt,
                    config: { temperature: 0.7 }
                });

                // Simple extraction
                const socialMatch = copyText.match(/SOCIAL:\s*(.*)/i);
                const emailMatch = copyText.match(/EMAIL:\s*(.*)/i);

                if (socialMatch && emailMatch) {
                    generatedVariants.push({
                        hook,
                        socialPost: socialMatch[1].trim(),
                        emailSubject: emailMatch[1].trim(),
                        workerId
                    });
                }
            } catch (e) {
                console.warn(`[ZERO-DAY SWARM] ⚠️ ${workerId} failed to generate copy for hook. Skipping.`);
            }
        }));

        await Promise.all(workerPromises);

        const executionTimeMs = Date.now() - startTime;
        console.log(`[ZERO-DAY SWARM] 🏁 Swarm execution complete!`);
        console.log(`[ZERO-DAY SWARM] 📊 Generated ${generatedVariants.length}/${hooks.length} copy variants in ${executionTimeMs}ms.`);
        console.log(`[ZERO-DAY SWARM] 💰 Net API Cost for bulk copy: $0.00 (Routed to RTX 4090)`);

        return {
            campaignHooks: hooks,
            generatedCopy: generatedVariants,
            executionTimeMs
        };
    }
);
