/**
 * @inception/cowork-bridge — Context Generator
 *
 * Generates CLAUDE.md-compatible context files for each agent.
 * Reads agent constitutions, ownership maps, and dispatch state
 * to produce rich context that Claude Cowork can consume.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';

export interface AgentContext {
  agentId: string;
  role: string;
  constitution: string;
  capabilities: string[];
  activeWorkstreams: string[];
  peers: string[];
  modelBackend: string;
}

export interface ContextGeneratorConfig {
  rootDir: string;
  constitutionDir: string;
  ownershipPath: string;
  outputDir: string;
}

export class ContextGenerator {
  private config: ContextGeneratorConfig;

  constructor(config: ContextGeneratorConfig) {
    this.config = config;
  }

  /** Load agent ownership map */
  private loadOwnership(): Record<string, any> {
    const raw = readFileSync(this.config.ownershipPath, 'utf-8');
    return JSON.parse(raw);
  }

  /** Load an agent's constitution */
  private loadConstitution(agentId: string): string {
    const constitutionPath = join(
      this.config.constitutionDir,
      `${agentId}.md`
    );
    if (!existsSync(constitutionPath)) {
      return `No constitution found for agent: ${agentId}`;
    }
    return readFileSync(constitutionPath, 'utf-8');
  }

  /** Build context for a single agent */
  buildAgentContext(agentId: string): AgentContext {
    const ownership = this.loadOwnership();
    const agentEntry = ownership.agents?.[agentId] || {};

    return {
      agentId,
      role: agentEntry.role || 'unassigned',
      constitution: this.loadConstitution(agentId),
      capabilities: agentEntry.capabilities || [],
      activeWorkstreams: agentEntry.workstreams || [],
      peers: agentEntry.peers || [],
      modelBackend: agentEntry.backend || 'claude-sonnet',
    };
  }

  /** Generate CLAUDE.md content for an agent */
  generateClaudeMd(context: AgentContext): string {
    const lines: string[] = [
      `# CLAUDE.md - ${context.agentId}`,
      '',
      `## Role`,
      context.role,
      '',
      `## Constitution`,
      context.constitution,
      '',
      `## Capabilities`,
      ...context.capabilities.map(c => `- ${c}`),
      '',
      `## Active Workstreams`,
      ...context.activeWorkstreams.map(w => `- ${w}`),
      '',
      `## Peer Agents`,
      ...context.peers.map(p => `- ${p}`),
      '',
      `## Model Backend`,
      context.modelBackend,
      '',
      `---`,
      `Generated by @inception/cowork-bridge context-generator`,
    ];
    return lines.join('\n');
  }

  /** Write CLAUDE.md for a specific agent */
  writeAgentContext(agentId: string): void {
    const context = this.buildAgentContext(agentId);
    const content = this.generateClaudeMd(context);
    const outputPath = join(
      this.config.outputDir,
      agentId,
      'CLAUDE.md'
    );
    writeFileSync(outputPath, content, 'utf-8');
  }

  /** Generate context for all agents in ownership map */
  writeAllAgentContexts(): string[] {
    const ownership = this.loadOwnership();
    const agentIds = Object.keys(ownership.agents || {});

    for (const agentId of agentIds) {
      this.writeAgentContext(agentId);
    }

    return agentIds;
  }
}

/** Create a ContextGenerator with sensible defaults */
export function createContextGenerator(
  config?: Partial<ContextGeneratorConfig>
): ContextGenerator {
  const rootDir = config?.rootDir || process.cwd();
  const defaults: ContextGeneratorConfig = {
    rootDir,
    constitutionDir: join(rootDir, 'constitutions'),
    ownershipPath: join(rootDir, '.cowork', 'agent-ownership.json'),
    outputDir: join(rootDir, '.cowork', 'contexts'),
  };
  return new ContextGenerator({ ...defaults, ...config });
}